FROM oven/bun:1-alpine AS deps
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --production --frozen-lockfile

FROM oven/bun:1-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production \
    PORT=3001 \
    LOG_PRETTY=false

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN chmod +x ./docker-entrypoint.sh

EXPOSE 3001
CMD ["./docker-entrypoint.sh"]
