services:

  postgres:
    image: postgis/postgis:17-3.5

    environment:
      POSTGRES_DB: appbit
      POSTGRES_USER: appbit
      POSTGRES_PASSWORD: appbit

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: